### ISSUE TITLE
exception: asset register

### ISSUE THREAD

**Issue by pmullaney** [hyperledger/hyperledger-server#11]
running into an exception during asset registration using current head of git repo for both hl server and cli. The output from the server follows, any help much appreciated.

mix phoenix.server[info] Running Hyperledger.Endpoint with Cowboy on port 4000 (http)
[info] POST /assets
[info] Processing by Hyperledger.AssetController.create/2
  Parameters: %{"asset" => %{"hash" => "3817a7b25f5a1e07cf8ff665f8f2bd4be1a5ec0a0fa0af2dacaa690288282dcf", "primaryAccountPublicKey" => "046D7F237F19E913A79DEC072CEC0888958DDB79B65084186943F19B062E8C65479638B7EFB0C363592C027D4C29A270976F64D661AE5502DD74D07C60C077DAF7", "publicKey" => "04DB5077CBC92E90E4E749EA5E740FF3FFC189FED26A46620F1B9604BEF3CAF6D7B3B209FDB12315A340B264722FBE54DCFC9C57C14DBB9E981B2344892E73EE59"}, "format" => "uber"}
  Pipelines: [:api]
[debug] BEGIN [] (72.5ms)
[debug] SELECT l0."id", l0."view", l0."command", l0."data", l0."authentication_key", l0."signature", l0."prepared", l0."committed", l0."executed", l0."inserted_at", l0."updated_at" FROM "log_entries" AS l0 [] (1.0ms)
[debug] BEGIN [] (0.5ms)
[debug] INSERT INTO "log_entries" ("authentication_key", "command", "committed", "data", "executed", "id", "inserted_at", "prepared", "signature", "updated_at", "view") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id" ["04DB5077CBC92E90E4E749EA5E740FF3FFC189FED26A46620F1B9604BEF3CAF6D7B3B209FDB12315A340B264722FBE54DCFC9C57C14DBB9E981B2344892E73EE59", "asset/create", false, "{\"asset\":{\"publicKey\":\"04DB5077CBC92E90E4E749EA5E740FF3FFC189FED26A46620F1B9604BEF3CAF6D7B3B209FDB12315A340B264722FBE54DCFC9C57C14DBB9E981B2344892E73EE59\",\"hash\":\"3817a7b25f5a1e07cf8ff665f8f2bd4be1a5ec0a0fa0af2dacaa690288282dcf\",\"primaryAccountPublicKey\":\"046D7F237F19E913A79DEC072CEC0888958DDB79B65084186943F19B062E8C65479638B7EFB0C363592C027D4C29A270976F64D661AE5502DD74D07C60C077DAF7\"}}", false, 1, {{2015, 7, 2}, {20, 45, 3, 0}}, false, "3046022100C41423909AAD0D82B6D5E8846962785E98A85C11C7691054F1A0E4D9A5F27A4602210095CD96C3BE95BDDE4F371E8D67FB077D2B652DE0188E4459C647A2146A412E2B", {{2015, 7, 2}, {20, 45, 3, 0}}, 1] (1.2ms)
[debug] COMMIT [] (0.0ms)
[debug] SELECT n0."id", n0."url", n0."public_key", n0."inserted_at", n0."updated_at" FROM "nodes" AS n0 WHERE (n0."url" = $1) ["http://localhost:4000"] (1.8ms)
[debug] BEGIN [] (0.3ms)
[debug] BEGIN [] (0.3ms)
[debug] INSERT INTO "prepare_confirmations" ("data", "inserted_at", "log_entry_id", "node_id", "signature", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id" [nil, {{2015, 7, 2}, {20, 45, 3, 0}}, 1, 1, "temp_signature", {{2015, 7, 2}, {20, 45, 3, 0}}] (0.7ms)
[debug] COMMIT [] (0.0ms)
[debug] SELECT p0."id", p0."signature", p0."data", p0."inserted_at", p0."updated_at", p0."log_entry_id", p0."node_id" FROM "prepare_confirmations" AS p0 WHERE (p0."log_entry_id" IN ($1)) [1] (1.0ms)
[debug] SELECT n0."id", n0."url", n0."public_key", n0."inserted_at", n0."updated_at" FROM "nodes" AS n0 [] (0.4ms)
[debug] BEGIN [] (0.2ms)
[debug] UPDATE "log_entries" SET "authentication_key" = $1, "command" = $2, "committed" = $3, "data" = $4, "executed" = $5, "inserted_at" = $6, "prepared" = $7, "signature" = $8, "updated_at" = $9, "view" = $10 WHERE "id" = $11 RETURNING "id" ["04DB5077CBC92E90E4E749EA5E740FF3FFC189FED26A46620F1B9604BEF3CAF6D7B3B209FDB12315A340B264722FBE54DCFC9C57C14DBB9E981B2344892E73EE59", "asset/create", false, "{\"asset\":{\"publicKey\":\"04DB5077CBC92E90E4E749EA5E740FF3FFC189FED26A46620F1B9604BEF3CAF6D7B3B209FDB12315A340B264722FBE54DCFC9C57C14DBB9E981B2344892E73EE59\",\"hash\":\"3817a7b25f5a1e07cf8ff665f8f2bd4be1a5ec0a0fa0af2dacaa690288282dcf\",\"primaryAccountPublicKey\":\"046D7F237F19E913A79DEC072CEC0888958DDB79B65084186943F19B062E8C65479638B7EFB0C363592C027D4C29A270976F64D661AE5502DD74D07C60C077DAF7\"}}", false, {{2015, 7, 2}, {20, 45, 3, 0}}, true, "3046022100C41423909AAD0D82B6D5E8846962785E98A85C11C7691054F1A0E4D9A5F27A4602210095CD96C3BE95BDDE4F371E8D67FB077D2B652DE0188E4459C647A2146A412E2B", {{2015, 7, 2}, {20, 45, 3, 0}}, 1, 1] (0.6ms)
[debug] COMMIT [] (0.0ms)
[info] Log entry 1 prepared
[debug] SELECT n0."id", n0."url", n0."public_key", n0."inserted_at", n0."updated_at" FROM "nodes" AS n0 WHERE (n0."url" = $1) ["http://localhost:4000"] (0.3ms)
[debug] BEGIN [] (0.2ms)
[debug] BEGIN [] (0.2ms)
[debug] INSERT INTO "commit_confirmations" ("data", "inserted_at", "log_entry_id", "node_id", "signature", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id" [nil, {{2015, 7, 2}, {20, 45, 3, 0}}, 1, 1, "temp_signature", {{2015, 7, 2}, {20, 45, 3, 0}}] (0.5ms)
[debug] COMMIT [] (0.0ms)
[debug] SELECT c0."id", c0."signature", c0."data", c0."inserted_at", c0."updated_at", c0."log_entry_id", c0."node_id" FROM "commit_confirmations" AS c0 WHERE (c0."log_entry_id" IN ($1)) [1] (0.4ms)
[debug] SELECT n0."id", n0."url", n0."public_key", n0."inserted_at", n0."updated_at" FROM "nodes" AS n0 [] (0.3ms)
[debug] BEGIN [] (0.2ms)
[debug] UPDATE "log_entries" SET "authentication_key" = $1, "command" = $2, "committed" = $3, "data" = $4, "executed" = $5, "inserted_at" = $6, "prepared" = $7, "signature" = $8, "updated_at" = $9, "view" = $10 WHERE "id" = $11 RETURNING "id" ["04DB5077CBC92E90E4E749EA5E740FF3FFC189FED26A46620F1B9604BEF3CAF6D7B3B209FDB12315A340B264722FBE54DCFC9C57C14DBB9E981B2344892E73EE59", "asset/create", true, "{\"asset\":{\"publicKey\":\"04DB5077CBC92E90E4E749EA5E740FF3FFC189FED26A46620F1B9604BEF3CAF6D7B3B209FDB12315A340B264722FBE54DCFC9C57C14DBB9E981B2344892E73EE59\",\"hash\":\"3817a7b25f5a1e07cf8ff665f8f2bd4be1a5ec0a0fa0af2dacaa690288282dcf\",\"primaryAccountPublicKey\":\"046D7F237F19E913A79DEC072CEC0888958DDB79B65084186943F19B062E8C65479638B7EFB0C363592C027D4C29A270976F64D661AE5502DD74D07C60C077DAF7\"}}", false, {{2015, 7, 2}, {20, 45, 3, 0}}, true, "3046022100C41423909AAD0D82B6D5E8846962785E98A85C11C7691054F1A0E4D9A5F27A4602210095CD96C3BE95BDDE4F371E8D67FB077D2B652DE0188E4459C647A2146A412E2B", {{2015, 7, 2}, {20, 45, 3, 0}}, 1, 1] (0.4ms)
[debug] COMMIT [] (0.0ms)
[info] Log entry 1 comitted
[debug] SELECT l0."id", l0."view", l0."command", l0."data", l0."authentication_key", l0."signature", l0."prepared", l0."committed", l0."executed", l0."inserted_at", l0."updated_at" FROM "log_entries" AS l0 WHERE (l0."id" = $1) [0] (0.3ms)
[debug] BEGIN [] (0.2ms)
[debug] BEGIN [] (0.8ms)
[debug] ROLLBACK [] (0.3ms)
[debug] ROLLBACK [] (0.2ms)
[debug] ROLLBACK [] (0.3ms)
[debug] ROLLBACK [] (0.3ms)
[debug] ROLLBACK [] (0.3ms)
[info] Sent 500 in 268ms
[error] #PID<0.293.0> running Hyperledger.Endpoint terminated
Server: 10.0.3.11:4000 (http)
Request: POST /assets
** (exit) an exception was raised:
    ** (ArgumentError) cannot insert/update an invalid changeset
        (ecto) lib/ecto/repo/model.ex:132: Ecto.Repo.Model.struct_from_changeset!/1
        (ecto) lib/ecto/repo/model.ex:14: Ecto.Repo.Model.insert/4
        (hyperledger) web/models/asset.ex:37: anonymous fn/1 in Hyperledger.Asset.create/1
        (ecto) lib/ecto/adapters/sql.ex:442: Ecto.Adapters.SQL.transaction/3
        (hyperledger) web/models/log_entry.ex:155: anonymous fn/1 in Hyperledger.LogEntry.execute/1
        (ecto) lib/ecto/adapters/sql.ex:442: Ecto.Adapters.SQL.transaction/3
        (hyperledger) web/models/log_entry.ex:122: anonymous fn/3 in Hyperledger.LogEntry.add_prepare/3
        (ecto) lib/ecto/adapters/sql.ex:442: Ecto.Adapters.SQL.transaction/3

**Comment by meetreks** [comment]
I am getting the same. I have asked Daniel to get a API which can be used rather than using command line. Awaiting response currently.
