### ISSUE TITLE
Server Installation Step 7 help request

### ISSUE THREAD

**Issue by aesca** [hyperledger/hyperledger-server#14]
Hello,

Can you please explain a bit step 7.  I have node downloaded

C:\Program Files\nodejs

unclear on the installation process

Much appreciated!

**Comment by danoprey** [comment]
Hi Andrew,

As mentioned, we are no longer maintaining/supporting this repo in anyway, I'm afraid. We also don't recommend using it for anything other than educational purposes and suggest holding off until the Java version is available.

We will be closing down this repo shortly.

**Comment by aesca** [comment]
Hi Dan,

I appreciate taking the time to respond to it regardless.  I look forward
to checking it out.  Best to you and your team.

Andrew
