### ISSUE TITLE
phoenix.server Errror: Cannot find module '/.../brunch'

### ISSUE THREAD

**Issue by sweyn** [hyperledger/hyperledger-server#5]
On Ubuntu 14.04 64bit:
$:mix phoenix.server
[info] Running Hyperledger.Endpoint with Cowboy on port 4000 (http)

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/USER/git/hyperledger-server/node_modules/brunch/bin/brunch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

[info] GET /
[info] Processing by Hyperledger.PageController.index/2
  Parameters: %{"format" => "uber"}
  Pipelines: [:api]
[info] Sent 200 in 44ms
[info] GET /favicon.ico
[info] GET /
[info] Processing by Hyperledger.PageController.index/2
  Parameters: %{"format" => "uber"}
  Pipelines: [:api]
[info] Sent 200 in 738µs

**Comment by DanielFeichtinger** [comment]
Hi there — thanks for pointing that out. I added a dependency to [Brunch](http://brunch.io) but I didn't update the install steps. It's currently unused and I may remove.

Anyway, to fix, install node.js, and run `npm install` in the project directory. Let me know if that doesn't work.
