### ISSUE TITLE
Error starting Database

### ISSUE THREAD

**Issue by getachew** [hyperledger/hyperledger-server#6]
Apologies if this creates unnecessary noise but being new to Erlang couldn't follow the error messages Followed the instructions on the homepage but I am getting the following error on step 4. I will be happy to dockerize the server as soon as I resolve this issue.

** (KeyError) key :database not found in: [otp_app: :hyperledger, adapter: Ecto.Adapters.Postgres]
    (elixir) lib/keyword.ex:165: Keyword.fetch!/2
    (ecto) lib/ecto/adapters/postgres.ex:67: Ecto.Adapters.Postgres.storage_up/1
    (ecto) lib/mix/tasks/ecto.create.ex:33: Mix.Tasks.Ecto.Create.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2

**Comment by DanielFeichtinger** [comment]
Hi there, I just pushed some better install steps to the repo — can you give those a try and let me know if that works for you? Would be great to get this in a container!

**Comment by getachew** [comment]
Thanks Daniel. The new steps clarified things and now it's up! 

I set my environment variable in the .env file as
DATABASE_URL=ecto://postgres:mysecretpassword@localhost/hl_dev

**Comment by getachew** [comment]
Hey @DanielFeichtinger following up on containerizing the server. Made some progress but had some questions I posted on the forum in detail. http://forum.hyperledger.com/t/containerizing-hyperledger-server/269/1

Please check it out and I would really appreciate your feedback to see if it is a good start.
