### ISSUE TITLE
Not able to start server

### ISSUE THREAD

**Issue by meetreks** [hyperledger/hyperledger-server#7]
Hi,

I got the dependencies sorted.

Then I created the hyperledger database which got created but for some reason, the control did not return to the command prompt.
When i tried migrate, no response.
When I tried starting phoenix.server no response.

Any logs where I can look and see?

What Should I do from here.

Cheers,
meetreks

**Comment by DanielFeichtinger** [comment]
Hi Meetreks,

Could you give me some more info about your system? For example, what OS are you using, and can you run the Elixir REPL with `iex -S mix`

Cheers,

Daniel
