### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by StephenHarrington** [hyperledger/hyperledger-server#8]
Hi Dan,

The dependencies for installing the server seem to have changed, the instructions (README.md) with the mix commands return an error, can't find configuration file. The deps directory is gone and I see you replaced it with mix.lock and mix.exs.  Can you provide an updated server install instructions?  Thank you!

Steve

**Comment by DanielFeichtinger** [comment]
Hi Steve,

I don't believe I've changed anything with the dependencies… the mix file should always have been there. The first install step, `mix deps.get`, should use the mix file to download the dependencies. What's the outcome of that step for you?

Daniel

**Comment by meetreks** [comment]
Daniel is right. I have used the same and all my dependencies have been installed.
